# Generated by Django 4.1.3 on 2022-11-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='prodcuts',
            new_name='prodcut',
        ),
    ]
