# Generated by Django 4.1.3 on 2022-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_prodcuts_review_prodcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='prodcut',
            new_name='product',
        ),
    ]
